const weeks_in_month = 5.333;
const weeks_in_year = 52.18;
let tax_bracket_floor = 37950.00;
let tax_rate = 0.25;
let tax_bracket_base = 5226.00;
let mdlive_gross_annual_income = 57000.00;
let mdlive_gross_weekly_income = mdlive_gross_annual_income/weeks_in_year;
let mdlive_gross_biweekly_income = mdlive_gross_annual_income/weeks_in_year/2;
let mdlive_monthly_gross_income = mdlive_gross_annual_income/12;
let mdlive_fiscal_gross_income = mdlive_monthly_gross_income*11;
let incruises_hourly_rate = 20.00;
let incruises_fulltime_weekly_hours = 40;
let incruises_partime_weekly_hours = 10;
let incruises_fulltime_weekly_gross_income = incruises_hourly_rate * incruises_fulltime_weekly_hours;
let incruises_fulltime_monthly_gross_income = incruises_fulltime_weekly_gross_income * weeks_in_month;
let incruises_partime_weekly_gross_income = incruises_hourly_rate * incruises_partime_weekly_hours;
let incruises_partime_monthly_gross_income = incruises_partime_weekly_gross_income*weeks_in_month;
let incruises_partime_annual_gross_income = incruises_partime_weekly_hours * weeks_in_year;
let incruises_fiscal_gross_income = incruises_fulltime_monthly_gross_income+incruises_partime_monthly_gross_income*11;
let gross_annual_income = incruises_partime_annual_gross_income + mdlive_gross_annual_income;
let gross_fiscal_income = incruises_fiscal_gross_income + mdlive_fiscal_gross_income;
let mdlive_annual_taxes = (mdlive_gross_annual_income)*tax_rate - tax_bracket_base;
let mdlive_net_annual_income = mdlive_gross_annual_income - mdlive_annual_taxes;
let mdlive_net_weekly_income = mdlive_net_annual_income/weeks_in_year;
let mdlive_net_biweekly_income = mdlive_net_weekly_income*2;
let fiscal_taxes = (gross_annual_income)*tax_rate-tax_bracket_base;
let taxed_fiscal_income = gross_fiscal_income - fiscal_taxes;
let taxed_fiscal_monthly_income = taxed_fiscal_income/12;
let taxed_fiscal_weekly_income = taxed_fiscal_income/weeks_in_year;
let cable_monthly_bill = 110.00;
let electricity_monthly_bill = 50.00;
let gas_monthly_bill = 15.00;
let utilities_monthly_expense = cable_monthly_bill + electricity_monthly_bill + gas_monthly_bill;
let utilities_annual_expense = utilities_monthly_expense*12;
let current_rent_monthly_expense = 1100.00;
let lucy_rent_monthly_expense = 1500.00;
let lucy_rent_annual_expense = lucy_rent_monthly_expense*12;
let rent_fiscal_expense = current_rent_monthly_expense*2 + lucy_rent_monthly_expense*10;
let groceries_weekly_expense = 100.00;
let groceries_annual_expense = groceries_weekly_expense*weeks_in_year;
let fiscal_expenses = rent_fiscal_expense + utilities_annual_expense;
let annual_expenses = lucy_rent_annual_expense + utilities_annual_expense + groceries_annual_expense;
let net_fiscal_income = taxed_fiscal_income - fiscal_expenses;
let net_fiscal_monthly_income = net_fiscal_income/12;
let net_fiscal_weekly_income = net_fiscal_income/weeks_in_year;
let savings_rate = 0.40;
let fiscal_savings = net_fiscal_income*savings_rate;
let fiscal_monthly_savings = fiscal_savings/12;
let fiscal_weekly_savings = fiscal_savings/weeks_in_year;
let fiscal_disposable_income = net_fiscal_income - fiscal_savings;
let fiscal_weekly_disposable_income = fiscal_disposable_income/weeks_in_year;
let fiscal_monthly_disposable_income = fiscal_disposable_income/12;


console.log("This Fiscal Year:");
console.log(`Gross Income: ${gross_fiscal_income}`);
console.log(`Taxes: ${fiscal_taxes}`);
console.log(`Taxed Income: ${taxed_fiscal_income}`);
console.log(`Taxed Monthly Income: ${taxed_fiscal_monthly_income}`);
console.log(`Taxed Monthly Income: ${taxed_fiscal_weekly_income}`);
console.log(`Expenses: ${fiscal_expenses}`);
console.log(`Net Income: ${net_fiscal_income}`);
console.log(`Net Monthly Income: ${net_fiscal_monthly_income}`);
console.log(`Net Weekly Income: ${net_fiscal_weekly_income}`);
console.log(`Savings: ${fiscal_savings}`);
console.log(`Monthly Savings: ${fiscal_monthly_savings}`);
console.log(`Weekly Savings: ${fiscal_weekly_savings}`);
console.log(`Disposable Income:${fiscal_disposable_income}`);
console.log(`Monthly Disposable Income: ${fiscal_monthly_disposable_income}`);
console.log(`Weekly Disposable Income: ${fiscal_weekly_disposable_income}`);
console.log(`MDLive Biweekly Income: ${mdlive_net_biweekly_income}`);
